config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :admins

  devise_for :admins
  resources :properties

  resources :tennants

  devise_for :users
  resources :invoices

  resources :companies

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :tennant
  belongs_to :property
  validates_presence_of :tennant, :property, :status
  validates_associated :tennant, :property

  validates_numericality_of :price, :greater_than_or_equal_to => 0, :allow_blank => false
  validates_numericality_of :amount_paid, :greater_than_or_equal_to => 0, :allow_blank => true

  def self.STATUS_NOT_PAID
    0
  end
  def self.STATUS_PAID
    1
  end
  def self.STATUS_PARTIAL_PAID
    2
  end

  def self.statuses
    [["Not Paid", Invoice.STATUS_NOT_PAID], ["Paid", Invoice.STATUS_PAID], ["Partially Paid", Invoice.STATUS_PARTIAL_PAID]]
  end

  def status_text
    self.class.statuses.each do |status|
      if status[1] == self.status
        return status[0]
      end
    end
    return nil
  end

  def row_class
    case status
      when self.class.STATUS_NOT_PAID
        "danger"
      when self.class.STATUS_PAID
        "success"
      when self.class.STATUS_PARTIAL_PAID
        "warning"
    end

  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @invoices = Invoice.all
    respond_with(@invoices)
  end

  def show
    respond_with(@invoice)
  end

  def new
    @invoice = Invoice.new
    respond_with(@invoice)
  end

  def edit
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.save
    respond_with(@invoice)
  end

  def update
    @invoice.update(invoice_params)
    respond_with(@invoice)
  end

  def destroy
    @invoice.destroy
    respond_with(@invoice)
  end

  private
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def invoice_params
      params.require(:invoice).permit(:price, :tennant_id, :property_id, :amount_paid, :status)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @invoice.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h4>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :tennant_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :tennant_id, Tennant.all, :id, :name, {}, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :property_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :property_id, Property.all, :id, :name, {}, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount_paid, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :amount_paid, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :status, Invoice.statuses, {}, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @invoice, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing invoice</h1>
</div>

<%= render 'form' %>

app/views/invoices/index.html.erb
<div class="page-header">
  <%= link_to new_invoice_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Invoice
  <% end %>
  <h1>Listing invoices</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Tennant</th>
            <th>Property</th>
            <th>Amount paid</th>
            <th>Price</th>
            <th>Status</th>
            <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
          <tr class="<%= invoice.row_class %>">
            <td><%= invoice.tennant.name %></td>
            <td><%= invoice.property.name %></td>
            <td><%= number_to_currency invoice.amount_paid %></td>
            <td><%= number_to_currency invoice.price %></td>
            <td><%= invoice.status_text %></td>
            <td>
              <%= link_to 'Show', invoice %><br />
              <%= link_to 'Edit', edit_invoice_path(invoice) %><br />
              <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/invoices/new.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New invoice</h1>
</div>

<%= render 'form' %>

app/views/invoices/show.html.erb
<div class="page-header">
  <%= link_to invoices_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_invoice_path(@invoice), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show invoice</h1>
</div>

<dl class="dl-horizontal">
  <dt>Price:</dt>
  <dd><%= number_to_currency @invoice.price %></dd>

  <dt>Tennant:</dt>
  <dd><%= @invoice.tennant.name %></dd>

  <dt>Property:</dt>
  <dd><%= @invoice.property.name %></dd>

  <dt>Amount paid:</dt>
  <dd><%= number_to_currency @invoice.amount_paid %></dd>

  <dt>Status:</dt>
  <dd><%= @invoice.status_text %></dd>

</dl>