config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :admins

  devise_for :admins
  resources :properties

  resources :tennants

  devise_for :users
  resources :invoices

  resources :companies

end

app/models/tennant.rb
class Tennant < ActiveRecord::Base
  belongs_to :property

  validates_associated :property, :allow_blank => false

  validates_presence_of :phone_number, :address, :city, :country, :is_active, :property
  validates_numericality_of :security_deposit, :greater_than_or_equal_to => 0

  before_save :before_save

  attr_reader :password

  def before_save
    if password.present?
      self.encrypted_password = BCrypt::Engine.hash_secret(password, BCRYPT_SALT)
    end
  end

  def after_save
    self.encrypted_password = nil
  end
end

app/controllers/tennants_controller.rb
class TennantsController < ApplicationController
  before_action :set_tennant, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tennants = Tennant.all
    respond_with(@tennants)
  end

  def show
    respond_with(@tennant)
  end

  def new
    @tennant = Tennant.new
    respond_with(@tennant)
  end

  def edit
  end

  def create
    @tennant = Tennant.new(tennant_params)
    @tennant.save
    respond_with(@tennant)
  end

  def update
    @tennant.update(tennant_params)
    respond_with(@tennant)
  end

  def destroy
    @tennant.destroy
    respond_with(@tennant)
  end

  private
    def set_tennant
      @tennant = Tennant.find(params[:id])
    end

    def tennant_params
      params.require(:tennant).permit(:property_id, :name, :username, :encrypted_password, :email, :phone_number, :address, :city, :country, :is_active)
    end
end

app/helpers/tennants_helper.rb
module TennantsHelper
end

app/views/tennants/_form.html.erb
<%= form_for(@tennant, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @tennant.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tennant.errors.count, "error") %> prohibited this tennant from being saved:</h4>

      <ul>
      <% @tennant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :property_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :property_id, Property.all, :id, :name, {:include_blank => true}, {:class => "form-control"} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :username, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :username, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.email_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :security_deposit, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :security_deposit, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :country, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_active, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_active, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tennants/edit.html.erb
<div class="page-header">
  <%= link_to tennants_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @tennant, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing tennant</h1>
</div>

<%= render 'form' %>

app/views/tennants/index.html.erb
<div class="page-header">
  <%= link_to new_tennant_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Tennant
  <% end %>
  <h1>Listing tennants</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Property</th>
            <th>Name</th>
            <th>Username</th>
            <th>Email</th>
            <th>Phone number</th>
            <th>Address</th>
            <th>City</th>
            <th>Country</th>
            <th>Is active</th>
            <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tennants) do |tennant| %>
            <td><%= tennant.property_id %></td>
            <td><%= tennant.name %></td>
            <td><%= tennant.username %></td>
            <td><%= tennant.email %></td>
            <td><%= tennant.phone_number %></td>
            <td><%= tennant.address %></td>
            <td><%= tennant.city %></td>
            <td><%= tennant.country %></td>
            <td><%= tennant.is_active %></td>
            <td>
                <%= link_to 'Show', tennant %><br />
                <%= link_to 'Edit', edit_tennant_path(tennant) %><br />
                <%= link_to 'Destroy', tennant, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tennants/new.html.erb
<div class="page-header">
  <%= link_to tennants_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New tennant</h1>
</div>

<%= render 'form' %>

app/views/tennants/show.html.erb
<div class="page-header">
  <%= link_to tennants_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_tennant_path(@tennant), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show tennant</h1>
</div>

<dl class="dl-horizontal">
  <dt>Property:</dt>
  <dd><%= @tennant.property.name %></dd>

  <dt>Name:</dt>
  <dd><%= @tennant.name %></dd>

  <dt>Username:</dt>
  <dd><%= @tennant.username %></dd>

  <dt>Email:</dt>
  <dd><%= @tennant.email %></dd>

  <dt>Phone number:</dt>
  <dd><%= @tennant.phone_number %></dd>

  <dt>Address:</dt>
  <dd><%= @tennant.address %></dd>

  <dt>City:</dt>
  <dd><%= @tennant.city %></dd>

  <dt>Country:</dt>
  <dd><%= @tennant.country %></dd>

  <dt>Is active:</dt>
  <dd><%= @tennant.is_active %></dd>

</dl>